name: find_it_app
description: "Lost and Found: Where Lost Items Find Their Way Home"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase integration
  supabase_flutter: ^1.10.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # State management
  provider: ^6.1.1
  
  # Image picking from gallery
  image_picker: ^1.0.4
  
  # App permissions
  permission_handler: ^12.0.1
  
  # HTTP requests
  http: ^1.1.0
  
  # Password hashing
  crypto: ^3.0.3
  flutter_secure_storage: ^10.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "FindIt.jpeg"